package com.devtrails.backend.service;

import com.devtrails.backend.client.AiServiceClient;
import com.devtrails.backend.dto.ClaimResponse;
import com.devtrails.backend.dto.FraudRequest;
import com.devtrails.backend.dto.FraudResponse;
import com.devtrails.backend.entity.AppUser;
import com.devtrails.backend.entity.Claim;
import com.devtrails.backend.entity.ClaimStatus;
import com.devtrails.backend.entity.Policy;
import com.devtrails.backend.entity.RiskData;
import com.devtrails.backend.entity.TriggerType;
import com.devtrails.backend.repository.ClaimRepository;
import com.devtrails.backend.repository.RiskDataRepository;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

@Service
@RequiredArgsConstructor
public class ClaimService {

    private final ClaimRepository claimRepository;
    private final PolicyService policyService;
    private final RiskDataRepository riskDataRepository;
    private final AiServiceClient aiServiceClient;

    public List<ClaimResponse> getClaimsForUser(Long userId) {
        return claimRepository.findByUserIdOrderByCreatedAtDesc(userId).stream().map(this::toResponse).toList();
    }

    public List<ClaimResponse> runTriggerEngine() {
        List<Claim> generated = new ArrayList<>();
        for (Policy policy : policyService.getActivePolicies()) {
            AppUser user = policy.getUser();
            RiskData riskData = riskDataRepository.findByCityAndZone(user.getCity(), user.getZone())
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Risk data not found"));
            generated.addAll(evaluatePolicy(policy, riskData));
        }
        return generated.stream().map(this::toResponse).toList();
    }

    private List<Claim> evaluatePolicy(Policy policy, RiskData riskData) {
        List<Claim> claims = new ArrayList<>();
        addIfPresent(claims, createClaimIfNeeded(policy, TriggerType.HEAVY_RAIN,
            riskData.getRainfallMm() != null && riskData.getRainfallMm() > 50, 6, "OpenWeather mock rainfall threshold"));
        addIfPresent(claims, createClaimIfNeeded(policy, TriggerType.HIGH_POLLUTION,
            riskData.getAqi() != null && riskData.getAqi() > 250, 5, "AQI threshold exceeded"));
        addIfPresent(claims, createClaimIfNeeded(policy, TriggerType.CURFEW,
            riskData.isCurfewActive(), 8, "Mock curfew / zone closure feed"));
        addIfPresent(claims, createClaimIfNeeded(policy, TriggerType.PLATFORM_DOWNTIME,
            riskData.isPlatformDowntime(), 4, "Mock platform outage feed"));
        return claims;
    }

    private void addIfPresent(List<Claim> claims, Claim claim) {
        if (claim != null) {
            claims.add(claim);
        }
    }

    private Claim createClaimIfNeeded(Policy policy, TriggerType triggerType,
                                      boolean shouldTrigger, int affectedHours, String source) {
        if (!shouldTrigger) {
            return null;
        }

        String eventKey = policy.getId() + "-" + triggerType + "-" + LocalDate.now();
        if (claimRepository.findByEventKey(eventKey).isPresent()) {
            return null;
        }

        AppUser user = policy.getUser();
        long duplicateClaims = claimRepository.findByUserIdOrderByCreatedAtDesc(user.getId()).stream()
            .filter(existing -> existing.getTriggerType() == triggerType)
            .count();

        FraudResponse fraudResponse = aiServiceClient.detectFraud(FraudRequest.builder()
            .city(user.getCity())
            .zone(user.getZone())
            .triggerType(triggerType.name())
            .duplicateClaims((int) duplicateClaims)
            .claimsInLastWeek((int) duplicateClaims)
            .build());

        BigDecimal hourlyIncome = user.getAverageDailyEarnings()
            .divide(BigDecimal.valueOf(10), 2, RoundingMode.HALF_UP);
        BigDecimal payout = hourlyIncome.multiply(BigDecimal.valueOf(affectedHours))
            .min(policy.getWeeklyCoverageAmount())
            .setScale(2, RoundingMode.HALF_UP);

        Claim claim = new Claim();
        claim.setUser(user);
        claim.setPolicy(policy);
        claim.setTriggerType(triggerType);
        claim.setTriggerSource(source);
        claim.setEventDate(LocalDate.now());
        claim.setAffectedHours(affectedHours);
        claim.setPayoutAmount(payout);
        claim.setFraudScore(fraudResponse.getFraudScore());
        claim.setFlagged(fraudResponse.isFlagged());
        claim.setStatus(fraudResponse.isFlagged() ? ClaimStatus.PENDING : ClaimStatus.APPROVED);
        claim.setAutoGenerated(true);
        claim.setEventKey(eventKey);
        return claimRepository.save(claim);
    }

    public ClaimResponse payout(Long claimId) {
        Claim claim = claimRepository.findById(claimId)
            .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Claim not found"));
        claim.setStatus(ClaimStatus.PAID);
        return toResponse(claimRepository.save(claim));
    }

    public List<Claim> allClaims() {
        return claimRepository.findAll();
    }

    public ClaimResponse toResponse(Claim claim) {
        return ClaimResponse.builder()
            .id(claim.getId())
            .triggerType(claim.getTriggerType())
            .triggerSource(claim.getTriggerSource())
            .eventDate(claim.getEventDate())
            .affectedHours(claim.getAffectedHours())
            .payoutAmount(claim.getPayoutAmount())
            .status(claim.getStatus())
            .fraudScore(claim.getFraudScore())
            .flagged(claim.isFlagged())
            .build();
    }
}
